<?php
$default_model= 'YourAppBusinessWorker';
$models = ['YourAppBusinessWorker','game_worker'];
//$models = ['YourAppBusinessWorker'];
$model_router = [
    1=>'game_worker',
    2=>'game_worker',
    3=>'game_worker',
    4=>'game_worker',
    5=>'game_worker',
    6=>'game_worker',
    7=>'game_worker',
    8=>'game_worker',
    9=>'game_worker',
    10=>'game_worker',
    11=>'game_worker',
    12=>'game_worker',
    13=>'game_worker',
    14=>'game_worker',
    15=>'game_worker',
    16=>'game_worker',
    17=>'game_worker',
    18=>'game_worker',
    19=>'game_worker',
    20=>'game_worker',
    21=>'game_worker',
    22=>'game_worker',
    23=>'game_worker',
    24=>'game_worker',
    25=>'game_worker',
    26=>'game_worker',
    27=>'game_worker',
    28=>'game_worker',
    29=>'game_worker',
    30=>'game_worker',
    31=>'game_worker',
    32=>'game_worker',
    33=>'game_worker',
    34=>'game_worker',
    35=>'game_worker',
    36=>'game_worker'

];